export const names=['系统启动 / 复位','USB / UART1','8路LED','8位数码管','K1 / K2 / K3','五向导航键','蜂鸣器','温度采集','光照采集','霍尔传感器','振动传感器','RTC时钟','EEPROM存储','FM收音机 / 耳机','红外收发','扩展模块——RS485收发',...['SM步进电机','超声波测距','直流电机','电子秤','电子尺','电子转角测量器','RFID读卡器'].map(n=>'扩展模块——'+n)];
export const advice=['检查USB线、供电、烧录时钟与RST按键。','关闭串口助手，检查USB线与CH340。','检查对应LED、限流电阻与驱动焊点。','检查缺位/缺段对应的数码管与驱动焊点。','检查对应按键与焊点，确保先松开再按。','检查导航键、分压电阻与焊点。','检查蜂鸣器、驱动与焊点。','确认触摸的是Rt热敏电阻，检查分压电阻与ADC线路。','确认遮挡的是光敏电阻，检查分压电阻与ADC线路。','换磁铁方向，检查霍尔元件与焊点。','轻晃板子，检查振动元件与焊点。','检查RTC芯片、晶振、电池和焊点。','保留备份报告，检查存储芯片和总线焊点。','换已知正常耳机并移动到接收良好的位置；噪声不能证明收音正常。','对准红外头、移开遮挡，再换已知正常辅助板复测。','检查A-A、B-B、参考地；换已知正常辅助板复测。'];
advice.push('断电复查SM插头、ULN2003驱动和电机线序。','检查EXT接线、Echo/Trig和障碍物位置；用已知正常模块复测。','断电检查课程电机驱动模块与EXT接线；不要将裸电机直接接IO。','检查HX711模块、称重传感器、供电及空载稳定性。','检查电子尺供电、P1.1信号及滑动接触。','检查编码器A/B两相、供电及旋转操作。','使用课程MFRC522适配板和配套卡；复查EXT/SM接线，不能将普通裸模块直接接5V。');
export const CMD={HELLO:1,CAPABILITIES:2,PREPARE:16,START:17,STATUS:18,STOP:19,SNAPSHOT:20,BACKUP:21,ROLE:22,PROGRESS:23,ARM:32,SEND:33};
export function crc(bytes){let c=65535;for(const v of bytes){c^=v;for(let b=0;b<8;b++)c=c&1?(c>>>1)^0xa001:c>>>1;}return c;}
export function frame(cmd,seq,attempt=0,test=0,step=0,p=[]){const a=new Uint8Array(24);a.set([165,90,2,cmd,0,1,attempt&255,attempt>>>8,seq&255,seq>>>8,test,step,8,0]);a.set(p.slice(0,8),14);const c=crc(a.slice(2,22));a[22]=c&255;a[23]=c>>>8;return a;}
export function decode(a){if(a.length!==24||a[0]!==165||a[1]!==90||a[2]!==2||a[12]!==8||crc(a.slice(2,22))!==(a[22]|a[23]<<8))return null;return {cmd:a[3],src:a[4],dst:a[5],attempt:a[6]|a[7]<<8,seq:a[8]|a[9]<<8,test:a[10],step:a[11],flags:a[13],p:Array.from(a.slice(14,22)),raw:Array.from(a)};}
export function summary(items){return items.some(x=>x.status==='ABNORMAL')?'发现异常':items.some(x=>x.status!=='NORMAL')?'未完成':'本轮通过';}
export function median(a){const s=[...a].sort((x,y)=>x-y);return s[Math.floor(s.length/2)];}
export function threshold(a,id){return Math.max(id===8?2:4,Math.max(...a)-Math.min(...a)+(id===8?1:2));}
export function rtcTime(p){const b=v=>{if((v&15)>9||(v>>4)>9)throw Error('RTC字段不是合法BCD');return (v>>4)*10+(v&15);};const [s,m,h,d,mo,w,y]=p.map(b);if(s>59||m>59||h>23||d<1||mo<1||mo>12||w<1||w>7)throw Error('RTC字段超出范围');const t=Date.UTC(2000+y,mo-1,d,h,m,s);if(new Date(t).getUTCDate()!==d)throw Error('RTC日期无效');return t;}
export const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
