import {SerialTransport} from './serial-transport.js';
import {frame,decode,CMD} from './diagnostic-core.js';
export class Board {
 constructor(){this.seq=0;this.buf=[];this.waiter=null;this.log=[];this.rxCount=0;this.connected=false;this.chain=Promise.resolve();this.transport=new SerialTransport({onBytes:b=>this.receive(b)});this.transport.onDisconnect=()=>{this.connected=false;this.waiter?.reject(Error('连接中断'));this.waiter=null;};}
 async open(){try{this.info=await this.transport.open();this.connected=true;this.hello=await this.ask(CMD.HELLO);if(this.hello[1]!==2||this.hello[2]!==3||this.hello[3]!==0)throw Error('固件版本不符，请烧录新版统一HEX');return this;}catch(e){await this.transport.close().catch(()=>{});this.connected=false;throw e;}}
 receive(bytes){this.buf.push(...bytes);while(this.buf.length>=24){if(this.buf[0]!==165||this.buf[1]!==90){this.buf.shift();continue;}const r=decode(this.buf.slice(0,24));if(!r){this.buf.shift();continue;}this.buf.splice(0,24);this.rxCount++;const w=this.waiter;if(w&&r.seq===w.seq&&r.attempt===w.attempt&&r.test===w.test&&r.step===w.step&&r.cmd===(w.cmd|128)&&r.src===1&&r.dst===0&&r.flags===1){this.log.push({at:Date.now(),rx:r.raw});this.waiter=null;w.resolve(r.p);}}}
 async rejectProbe(bytes){await this.chain;const before=this.rxCount;await this.transport.send(bytes);await new Promise(r=>setTimeout(r,500));this.log.push({probe:Array.from(bytes),silent:this.rxCount===before});if(this.rxCount!==before)throw Error('无效帧未被拒绝');}
 async splitProbe(){await this.chain;const seq=this.seq=(this.seq+1)&65535;const b=frame(CMD.HELLO,seq);const result=new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.waiter=null;reject(Error('半帧补齐后未恢复'));},1700);this.waiter={seq,cmd:CMD.HELLO,attempt:0,test:0,step:0,resolve:p=>{clearTimeout(timer);resolve(p);},reject:e=>{clearTimeout(timer);reject(e);}};});const before=this.rxCount;await this.transport.send(b.slice(0,12));await new Promise(r=>setTimeout(r,150));if(this.rxCount!==before)throw Error('未补齐半帧就收到响应');this.log.push({halfFrameSilence:this.rxCount===before});await this.transport.send(b.slice(12));const p=await result;if(p[0])throw Error('半帧恢复响应异常');return p;}
 ask(cmd,attempt=0,test=0,step=0,p=[]){const run=()=>this.request(cmd,attempt,test,step,p);const task=this.chain.then(run,run);this.chain=task.catch(()=>{});return task;}
 async request(cmd,attempt,test,step,p){if(!this.connected)throw Error('连接中断');const seq=this.seq=(this.seq+1)&65535;const bytes=frame(cmd,seq,attempt,test,step,p);for(let retry=0;retry<2;retry++){try{const result=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.waiter=null;reject(Error('命令超时'));},1700);this.waiter={seq,cmd,attempt,test,step,resolve:v=>{clearTimeout(timer);resolve(v);},reject:e=>{clearTimeout(timer);reject(e);}};this.log.push({at:Date.now(),tx:Array.from(bytes),retry});this.transport.send(bytes).catch(e=>{this.waiter?.reject(e);this.waiter=null;});});if(result[0])throw Error(`设备拒绝命令（${result[0]}）`);return result;}catch(e){this.log.push({at:Date.now(),error:e.message,retry});if(!this.connected||e.message.includes('拒绝')||retry)throw e;}}}
 async close(){await this.transport.close();this.connected=false;}
}
