import {test} from 'node:test';
import assert from 'node:assert/strict';
import {names,advice,CMD} from '../../web/js/diagnostic-core.js';
import {changeRule,devices,signed,runExtension} from '../../web/js/extension-runner.js';
import {Runner} from '../../web/js/diagnostic-runner.js';
test('23 stable IDs, extension names and advice',()=>{assert.equal(names.length,23);assert.equal(advice.length,23);for(let i=15;i<23;i++)assert(names[i].startsWith('扩展模块——'));assert(names[21].includes('电子转角'));assert.equal(Object.keys(devices).length,7);});
test('fixed rules account for observed noise without user settings',()=>{assert.equal(changeRule([100,100,100],18).limit,5);assert.equal(changeRule([100,110,100],21).limit,32);assert.equal(signed([255,255]),-1);});
test('extension does not require auxiliary and cancellation does not pass',async()=>{const b={connected:true,ask:async()=>[0,0,0,0,0,0,0,0]};let r;r=new Runner(b,null,async()=>{},async()=>{},()=>{},async()=>{r.cancelled=true;throw Error('用户跳过或取消');});const result=await r.run(18,1);assert.equal(result.status,'UNTESTED');});
test('motor needs manual confirmation even when firmware sequence completes',async()=>{const data=[];const r={id:19,attempt:1,data,board:{},clock(){},report(){},check(){},checkpoint:async()=>{},reconnect:async()=>({}),q:async(c)=>{data.push(c);return c===CMD.STATUS?[3,0,0,0,5]:[0,0,0,0,0,0,0];},prompt:async()=>{},poll:async(read,test)=>{const p=await read();assert(test(p));return p;},manual:async()=>'确认超时'};assert.equal((await runExtension(r)).status,'UNTESTED');assert(data.includes(CMD.START));});
function extensionHarness(id){let step=0,reads=0,seq=0;const stages=[];const r={id,attempt:1,data:[],board:{},clock(){},report(){},check(){},checkpoint:async x=>stages.push(x),reconnect:async()=>({}),prompt:async()=>{},q:async(cmd,s=0)=>{if(cmd===CMD.START)step=s;if(cmd!==CMD.SNAPSHOT)return [0,0,0,0,0,0,0];reads++;seq++;const v=reads<=7?100:reads<=10?200:100;return [v,0,0,0,seq&255,seq>>8,1];},poll:async(read,test)=>{for(let n=0;n<30;n++){const p=await read();if(test(p))return p;}throw Error('timeout');}};return {r,stages};}
test('ultrasound baseline and change are required',async()=>{const {r,stages}=extensionHarness(18);assert.equal((await runExtension(r)).status,'NORMAL');assert.deepEqual(stages.filter(s=>s.stage).map(s=>s.stage),['baseline','changed']);});
test('scale and ruler require return-to-baseline evidence',async()=>{for(const id of [20,21]){const {r,stages}=extensionHarness(id);assert.equal((await runExtension(r)).status,'NORMAL');assert(stages.some(s=>s.stage==='restored'));}});
test('frozen sensor does not pass',async()=>{const {r}=extensionHarness(18);r.q=async()=>[100,0,0,0,1,0,1];await assert.rejects(runExtension(r),/timeout/);});
test('ruler wiring matches course ADC channel 1',()=>{assert(devices[21].wiring.includes('P1.1'));assert(!devices[21].wiring.includes('P1.0'));});
