#ifndef ACCEPTANCE_PLATFORM_TYPES_H
#define ACCEPTANCE_PLATFORM_TYPES_H

typedef enum CommandStatusTag {
    CMD_OK = 0x00,
    CMD_BUSY = 0x01,
    CMD_BAD_VERSION = 0x02,
    CMD_BAD_PARAM = 0x03,
    CMD_BAD_STATE = 0x04,
    CMD_UNSUPPORTED = 0x05,
    CMD_WRONG_SESSION = 0x06,
    CMD_BUFFER_FULL = 0x07,
    CMD_RESOURCE_CONFLICT = 0x08,
    CMD_RESTORE_REQUIRED = 0x09,
    CMD_LEASE_EXPIRED = 0x0A,
    CMD_RECORD_NOT_FOUND = 0x0B
} CommandStatus;

typedef enum TestVerdictTag {
    VERDICT_NOT_RUN = 0,
    VERDICT_RUNNING = 1,
    VERDICT_PASS = 2,
    VERDICT_FAIL = 3,
    VERDICT_BLOCKED = 4,
    VERDICT_INCONCLUSIVE = 5,
    VERDICT_SKIPPED = 6,
    VERDICT_ABORTED = 7
} TestVerdict;

typedef enum ReasonCodeTag {
    REASON_NONE = 0x00,
    REASON_RESPONSE_TIMEOUT = 0x01,
    REASON_DATA_MISMATCH = 0x02,
    REASON_NODE_UNREACHABLE = 0x03,
    REASON_PRECONDITION_MISSING = 0x04,
    REASON_USER_REJECTED = 0x05,
    REASON_USER_CANCELLED = 0x06,
    REASON_INVALID_SAMPLE = 0x07,
    REASON_EVIDENCE_GAP = 0x08,
    REASON_RESTORE_FAILED = 0x09,
    REASON_PROFILE_UNSUPPORTED = 0x0A,
    REASON_SCHEDULING_OVERLOAD = 0x0B,
    REASON_STORAGE_ERROR = 0x0C,
    REASON_REBOOT_DETECTED = 0x0D,
    REASON_STIMULUS_UNCONFIRMED = 0x0E,
    REASON_LEASE_EXPIRED = 0x0F
} ReasonCode;

#endif
